from . import (  # client,
    account_move,
    building,
    model_d,
    owner,
    property,
    property_history,
    property_offer,
    property_type,
    res_partner,
    sale_order,
    tag,
)
